import type { QuestionType } from '../../db/enums'
import { escapeHtml } from './html-utils'
import type { CoverageRow } from './coverage'

export interface KeyTemplateQuestion {
  position: number
  section: string
  marks: number
  type: QuestionType
  text: string
  answer: string
  diagram_kind: string | null
  correctOptionLabel: string | null
  stepMarks: Array<{ step_no: number; description: string; marks: number }>
}

export interface KeyTemplateInput {
  title: string
  questions: Array<KeyTemplateQuestion>
  coverage: Array<CoverageRow>
}

function renderExpectedAnswer(q: KeyTemplateQuestion): string {
  if (
    (q.type === 'mcq' || q.type === 'assertion_reason') &&
    q.correctOptionLabel
  ) {
    return `Correct option: <strong>${escapeHtml(q.correctOptionLabel)}</strong> — ${escapeHtml(q.answer)}`
  }
  return escapeHtml(q.answer)
}

function renderStepMarks(
  steps: Array<{ step_no: number; description: string; marks: number }>,
): string {
  if (steps.length === 0) return ''
  const sorted = [...steps].sort((a, b) => a.step_no - b.step_no)
  return `
    <table class="step-marks">
      <thead><tr><th>Step</th><th>What earns the mark</th><th>Marks</th></tr></thead>
      <tbody>
        ${sorted
          .map(
            (s) =>
              `<tr><td>${s.step_no}</td><td>${escapeHtml(s.description)}</td><td>${s.marks}</td></tr>`,
          )
          .join('')}
      </tbody>
    </table>`
}

function renderCoverageTable(coverage: Array<CoverageRow>): string {
  return `
    <table class="coverage">
      <thead>
        <tr><th>Concept</th><th>Questions</th><th>Marks</th><th>% Weight</th><th>Bloom split</th></tr>
      </thead>
      <tbody>
        ${coverage
          .map((row) => {
            const bloomSplit = Object.entries(row.bloom_split)
              .map(([bloom, count]) => `${bloom}: ${count}`)
              .join(', ')
            return `<tr>
              <td>${escapeHtml(row.concept_name)}</td>
              <td>${row.question_count}</td>
              <td>${row.marks}</td>
              <td>${row.weight_pct}%</td>
              <td>${escapeHtml(bloomSplit)}</td>
            </tr>`
          })
          .join('')}
      </tbody>
    </table>`
}

/**
 * F036/F037: answers, step-wise marks, and expected diagram description in one PDF that is
 * generated by an entirely separate route from the student paper (never bundled into that file),
 * plus the concept coverage & Bloom table (F037) appended at the end.
 */
export function buildAnswerKeyHtml(input: KeyTemplateInput): string {
  const sorted = [...input.questions].sort((a, b) => a.position - b.position)

  return `<!doctype html>
<html>
<head>
<meta charset="utf-8" />
<style>
  * { box-sizing: border-box; }
  body { font-family: Georgia, 'Times New Roman', serif; font-size: 11pt; color: #111; margin: 0; }
  h1 { font-size: 15pt; margin: 0 0 4px; }
  .warning { font-size: 9pt; color: #a00; margin-bottom: 12px; }
  .item { page-break-inside: avoid; margin-bottom: 10px; border-bottom: 1px solid #ddd; padding-bottom: 8px; }
  .item .item-head { font-weight: bold; }
  .item .marks { color: #444; font-weight: normal; }
  .diagram-desc { font-style: italic; color: #444; margin-top: 4px; }
  table.step-marks, table.coverage {
    border-collapse: collapse;
    width: 100%;
    margin-top: 6px;
    font-size: 9.5pt;
  }
  table.step-marks th, table.step-marks td,
  table.coverage th, table.coverage td {
    border: 1px solid #999;
    padding: 3px 6px;
    text-align: left;
  }
  h2.coverage-title { margin-top: 24px; font-size: 13pt; }
</style>
</head>
<body>
  <h1>${escapeHtml(input.title)} — Answer Key &amp; Marking Scheme</h1>
  <div class="warning">For teacher/parent use only. Never distribute this file to the student before the paper is attempted.</div>
  ${sorted
    .map(
      (q) => `
    <div class="item">
      <div class="item-head">${q.position}. [${q.section}] <span class="marks">(${q.marks} mark${q.marks === 1 ? '' : 's'})</span></div>
      <div>${renderExpectedAnswer(q)}</div>
      ${renderStepMarks(q.stepMarks)}
      ${q.diagram_kind ? `<div class="diagram-desc">Expected diagram: ${escapeHtml(q.diagram_kind)}</div>` : ''}
    </div>`,
    )
    .join('')}
  <h2 class="coverage-title">Concept Coverage &amp; Bloom Table</h2>
  ${renderCoverageTable(input.coverage)}
</body>
</html>`
}
