/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAttemptsRouteImport } from './routes/api/attempts'
import { Route as ApiBlueprintsRouteImport } from './routes/api/blueprints'
import { Route as ApiEvaluationsRouteImport } from './routes/api/evaluations'
import { Route as ApiQuestionsRouteImport } from './routes/api/questions'
import { Route as ApiStudentsRouteImport } from './routes/api/students'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiPapersIdRouteImport } from './routes/api/papers/$id'
import { Route as ApiPapersGenerateRouteImport } from './routes/api/papers/generate'
import { Route as ApiQuestionsIdRouteImport } from './routes/api/questions/$id'
import { Route as ApiStudentsIdRouteImport } from './routes/api/students/$id'
import { Route as ApiSyllabusChaptersRouteImport } from './routes/api/syllabus/chapters'
import { Route as ApiSyllabusSubjectsRouteImport } from './routes/api/syllabus/subjects'
import { Route as ApiTrackerStudentIdRouteImport } from './routes/api/tracker/$studentId'
import { Route as ApiAttemptsIdAnswerRouteImport } from './routes/api/attempts/$id/answer'
import { Route as ApiAttemptsIdSubmitRouteImport } from './routes/api/attempts/$id/submit'
import { Route as ApiEvaluationsIdConfirmRouteImport } from './routes/api/evaluations/$id/confirm'
import { Route as ApiEvaluationsIdReportRouteImport } from './routes/api/evaluations/$id/report'
import { Route as ApiPapersIdRegenerateSlotRouteImport } from './routes/api/papers/$id/regenerate-slot'
import { Route as ApiQuestionsIdApproveRouteImport } from './routes/api/questions/$id/approve'
import { Route as ApiEvaluationsIdItemsItemIdRouteImport } from './routes/api/evaluations/$id/items/$itemId'
import { Route as ApiSyllabusChaptersIdScopeRouteImport } from './routes/api/syllabus/chapters/$id/scope'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttemptsRoute = ApiAttemptsRouteImport.update({
  id: '/api/attempts',
  path: '/api/attempts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBlueprintsRoute = ApiBlueprintsRouteImport.update({
  id: '/api/blueprints',
  path: '/api/blueprints',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvaluationsRoute = ApiEvaluationsRouteImport.update({
  id: '/api/evaluations',
  path: '/api/evaluations',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuestionsRoute = ApiQuestionsRouteImport.update({
  id: '/api/questions',
  path: '/api/questions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudentsRoute = ApiStudentsRouteImport.update({
  id: '/api/students',
  path: '/api/students',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPapersIdRoute = ApiPapersIdRouteImport.update({
  id: '/api/papers/$id',
  path: '/api/papers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPapersGenerateRoute = ApiPapersGenerateRouteImport.update({
  id: '/api/papers/generate',
  path: '/api/papers/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQuestionsIdRoute = ApiQuestionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiQuestionsRoute,
} as any)
const ApiStudentsIdRoute = ApiStudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiStudentsRoute,
} as any)
const ApiSyllabusChaptersRoute = ApiSyllabusChaptersRouteImport.update({
  id: '/api/syllabus/chapters',
  path: '/api/syllabus/chapters',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyllabusSubjectsRoute = ApiSyllabusSubjectsRouteImport.update({
  id: '/api/syllabus/subjects',
  path: '/api/syllabus/subjects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackerStudentIdRoute = ApiTrackerStudentIdRouteImport.update({
  id: '/api/tracker/$studentId',
  path: '/api/tracker/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAttemptsIdAnswerRoute = ApiAttemptsIdAnswerRouteImport.update({
  id: '/$id/answer',
  path: '/$id/answer',
  getParentRoute: () => ApiAttemptsRoute,
} as any)
const ApiAttemptsIdSubmitRoute = ApiAttemptsIdSubmitRouteImport.update({
  id: '/$id/submit',
  path: '/$id/submit',
  getParentRoute: () => ApiAttemptsRoute,
} as any)
const ApiEvaluationsIdConfirmRoute = ApiEvaluationsIdConfirmRouteImport.update({
  id: '/$id/confirm',
  path: '/$id/confirm',
  getParentRoute: () => ApiEvaluationsRoute,
} as any)
const ApiEvaluationsIdReportRoute = ApiEvaluationsIdReportRouteImport.update({
  id: '/$id/report',
  path: '/$id/report',
  getParentRoute: () => ApiEvaluationsRoute,
} as any)
const ApiPapersIdRegenerateSlotRoute =
  ApiPapersIdRegenerateSlotRouteImport.update({
    id: '/regenerate-slot',
    path: '/regenerate-slot',
    getParentRoute: () => ApiPapersIdRoute,
  } as any)
const ApiQuestionsIdApproveRoute = ApiQuestionsIdApproveRouteImport.update({
  id: '/approve',
  path: '/approve',
  getParentRoute: () => ApiQuestionsIdRoute,
} as any)
const ApiEvaluationsIdItemsItemIdRoute =
  ApiEvaluationsIdItemsItemIdRouteImport.update({
    id: '/$id/items/$itemId',
    path: '/$id/items/$itemId',
    getParentRoute: () => ApiEvaluationsRoute,
  } as any)
const ApiSyllabusChaptersIdScopeRoute =
  ApiSyllabusChaptersIdScopeRouteImport.update({
    id: '/$id/scope',
    path: '/$id/scope',
    getParentRoute: () => ApiSyllabusChaptersRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/attempts': typeof ApiAttemptsRouteWithChildren
  '/api/blueprints': typeof ApiBlueprintsRoute
  '/api/evaluations': typeof ApiEvaluationsRouteWithChildren
  '/api/questions': typeof ApiQuestionsRouteWithChildren
  '/api/students': typeof ApiStudentsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/papers/$id': typeof ApiPapersIdRouteWithChildren
  '/api/papers/generate': typeof ApiPapersGenerateRoute
  '/api/questions/$id': typeof ApiQuestionsIdRouteWithChildren
  '/api/students/$id': typeof ApiStudentsIdRoute
  '/api/syllabus/chapters': typeof ApiSyllabusChaptersRouteWithChildren
  '/api/syllabus/subjects': typeof ApiSyllabusSubjectsRoute
  '/api/tracker/$studentId': typeof ApiTrackerStudentIdRoute
  '/api/attempts/$id/answer': typeof ApiAttemptsIdAnswerRoute
  '/api/attempts/$id/submit': typeof ApiAttemptsIdSubmitRoute
  '/api/evaluations/$id/confirm': typeof ApiEvaluationsIdConfirmRoute
  '/api/evaluations/$id/report': typeof ApiEvaluationsIdReportRoute
  '/api/papers/$id/regenerate-slot': typeof ApiPapersIdRegenerateSlotRoute
  '/api/questions/$id/approve': typeof ApiQuestionsIdApproveRoute
  '/api/evaluations/$id/items/$itemId': typeof ApiEvaluationsIdItemsItemIdRoute
  '/api/syllabus/chapters/$id/scope': typeof ApiSyllabusChaptersIdScopeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/attempts': typeof ApiAttemptsRouteWithChildren
  '/api/blueprints': typeof ApiBlueprintsRoute
  '/api/evaluations': typeof ApiEvaluationsRouteWithChildren
  '/api/questions': typeof ApiQuestionsRouteWithChildren
  '/api/students': typeof ApiStudentsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/papers/$id': typeof ApiPapersIdRouteWithChildren
  '/api/papers/generate': typeof ApiPapersGenerateRoute
  '/api/questions/$id': typeof ApiQuestionsIdRouteWithChildren
  '/api/students/$id': typeof ApiStudentsIdRoute
  '/api/syllabus/chapters': typeof ApiSyllabusChaptersRouteWithChildren
  '/api/syllabus/subjects': typeof ApiSyllabusSubjectsRoute
  '/api/tracker/$studentId': typeof ApiTrackerStudentIdRoute
  '/api/attempts/$id/answer': typeof ApiAttemptsIdAnswerRoute
  '/api/attempts/$id/submit': typeof ApiAttemptsIdSubmitRoute
  '/api/evaluations/$id/confirm': typeof ApiEvaluationsIdConfirmRoute
  '/api/evaluations/$id/report': typeof ApiEvaluationsIdReportRoute
  '/api/papers/$id/regenerate-slot': typeof ApiPapersIdRegenerateSlotRoute
  '/api/questions/$id/approve': typeof ApiQuestionsIdApproveRoute
  '/api/evaluations/$id/items/$itemId': typeof ApiEvaluationsIdItemsItemIdRoute
  '/api/syllabus/chapters/$id/scope': typeof ApiSyllabusChaptersIdScopeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/attempts': typeof ApiAttemptsRouteWithChildren
  '/api/blueprints': typeof ApiBlueprintsRoute
  '/api/evaluations': typeof ApiEvaluationsRouteWithChildren
  '/api/questions': typeof ApiQuestionsRouteWithChildren
  '/api/students': typeof ApiStudentsRouteWithChildren
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/papers/$id': typeof ApiPapersIdRouteWithChildren
  '/api/papers/generate': typeof ApiPapersGenerateRoute
  '/api/questions/$id': typeof ApiQuestionsIdRouteWithChildren
  '/api/students/$id': typeof ApiStudentsIdRoute
  '/api/syllabus/chapters': typeof ApiSyllabusChaptersRouteWithChildren
  '/api/syllabus/subjects': typeof ApiSyllabusSubjectsRoute
  '/api/tracker/$studentId': typeof ApiTrackerStudentIdRoute
  '/api/attempts/$id/answer': typeof ApiAttemptsIdAnswerRoute
  '/api/attempts/$id/submit': typeof ApiAttemptsIdSubmitRoute
  '/api/evaluations/$id/confirm': typeof ApiEvaluationsIdConfirmRoute
  '/api/evaluations/$id/report': typeof ApiEvaluationsIdReportRoute
  '/api/papers/$id/regenerate-slot': typeof ApiPapersIdRegenerateSlotRoute
  '/api/questions/$id/approve': typeof ApiQuestionsIdApproveRoute
  '/api/evaluations/$id/items/$itemId': typeof ApiEvaluationsIdItemsItemIdRoute
  '/api/syllabus/chapters/$id/scope': typeof ApiSyllabusChaptersIdScopeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/attempts'
    | '/api/blueprints'
    | '/api/evaluations'
    | '/api/questions'
    | '/api/students'
    | '/api/auth/$'
    | '/api/papers/$id'
    | '/api/papers/generate'
    | '/api/questions/$id'
    | '/api/students/$id'
    | '/api/syllabus/chapters'
    | '/api/syllabus/subjects'
    | '/api/tracker/$studentId'
    | '/api/attempts/$id/answer'
    | '/api/attempts/$id/submit'
    | '/api/evaluations/$id/confirm'
    | '/api/evaluations/$id/report'
    | '/api/papers/$id/regenerate-slot'
    | '/api/questions/$id/approve'
    | '/api/evaluations/$id/items/$itemId'
    | '/api/syllabus/chapters/$id/scope'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/attempts'
    | '/api/blueprints'
    | '/api/evaluations'
    | '/api/questions'
    | '/api/students'
    | '/api/auth/$'
    | '/api/papers/$id'
    | '/api/papers/generate'
    | '/api/questions/$id'
    | '/api/students/$id'
    | '/api/syllabus/chapters'
    | '/api/syllabus/subjects'
    | '/api/tracker/$studentId'
    | '/api/attempts/$id/answer'
    | '/api/attempts/$id/submit'
    | '/api/evaluations/$id/confirm'
    | '/api/evaluations/$id/report'
    | '/api/papers/$id/regenerate-slot'
    | '/api/questions/$id/approve'
    | '/api/evaluations/$id/items/$itemId'
    | '/api/syllabus/chapters/$id/scope'
  id:
    | '__root__'
    | '/'
    | '/api/attempts'
    | '/api/blueprints'
    | '/api/evaluations'
    | '/api/questions'
    | '/api/students'
    | '/api/auth/$'
    | '/api/papers/$id'
    | '/api/papers/generate'
    | '/api/questions/$id'
    | '/api/students/$id'
    | '/api/syllabus/chapters'
    | '/api/syllabus/subjects'
    | '/api/tracker/$studentId'
    | '/api/attempts/$id/answer'
    | '/api/attempts/$id/submit'
    | '/api/evaluations/$id/confirm'
    | '/api/evaluations/$id/report'
    | '/api/papers/$id/regenerate-slot'
    | '/api/questions/$id/approve'
    | '/api/evaluations/$id/items/$itemId'
    | '/api/syllabus/chapters/$id/scope'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiAttemptsRoute: typeof ApiAttemptsRouteWithChildren
  ApiBlueprintsRoute: typeof ApiBlueprintsRoute
  ApiEvaluationsRoute: typeof ApiEvaluationsRouteWithChildren
  ApiQuestionsRoute: typeof ApiQuestionsRouteWithChildren
  ApiStudentsRoute: typeof ApiStudentsRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiPapersIdRoute: typeof ApiPapersIdRouteWithChildren
  ApiPapersGenerateRoute: typeof ApiPapersGenerateRoute
  ApiSyllabusChaptersRoute: typeof ApiSyllabusChaptersRouteWithChildren
  ApiSyllabusSubjectsRoute: typeof ApiSyllabusSubjectsRoute
  ApiTrackerStudentIdRoute: typeof ApiTrackerStudentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attempts': {
      id: '/api/attempts'
      path: '/api/attempts'
      fullPath: '/api/attempts'
      preLoaderRoute: typeof ApiAttemptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/blueprints': {
      id: '/api/blueprints'
      path: '/api/blueprints'
      fullPath: '/api/blueprints'
      preLoaderRoute: typeof ApiBlueprintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/evaluations': {
      id: '/api/evaluations'
      path: '/api/evaluations'
      fullPath: '/api/evaluations'
      preLoaderRoute: typeof ApiEvaluationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/questions': {
      id: '/api/questions'
      path: '/api/questions'
      fullPath: '/api/questions'
      preLoaderRoute: typeof ApiQuestionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/students': {
      id: '/api/students'
      path: '/api/students'
      fullPath: '/api/students'
      preLoaderRoute: typeof ApiStudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/papers/$id': {
      id: '/api/papers/$id'
      path: '/api/papers/$id'
      fullPath: '/api/papers/$id'
      preLoaderRoute: typeof ApiPapersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/papers/generate': {
      id: '/api/papers/generate'
      path: '/api/papers/generate'
      fullPath: '/api/papers/generate'
      preLoaderRoute: typeof ApiPapersGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/questions/$id': {
      id: '/api/questions/$id'
      path: '/$id'
      fullPath: '/api/questions/$id'
      preLoaderRoute: typeof ApiQuestionsIdRouteImport
      parentRoute: typeof ApiQuestionsRoute
    }
    '/api/students/$id': {
      id: '/api/students/$id'
      path: '/$id'
      fullPath: '/api/students/$id'
      preLoaderRoute: typeof ApiStudentsIdRouteImport
      parentRoute: typeof ApiStudentsRoute
    }
    '/api/syllabus/chapters': {
      id: '/api/syllabus/chapters'
      path: '/api/syllabus/chapters'
      fullPath: '/api/syllabus/chapters'
      preLoaderRoute: typeof ApiSyllabusChaptersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/syllabus/subjects': {
      id: '/api/syllabus/subjects'
      path: '/api/syllabus/subjects'
      fullPath: '/api/syllabus/subjects'
      preLoaderRoute: typeof ApiSyllabusSubjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tracker/$studentId': {
      id: '/api/tracker/$studentId'
      path: '/api/tracker/$studentId'
      fullPath: '/api/tracker/$studentId'
      preLoaderRoute: typeof ApiTrackerStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/attempts/$id/answer': {
      id: '/api/attempts/$id/answer'
      path: '/$id/answer'
      fullPath: '/api/attempts/$id/answer'
      preLoaderRoute: typeof ApiAttemptsIdAnswerRouteImport
      parentRoute: typeof ApiAttemptsRoute
    }
    '/api/attempts/$id/submit': {
      id: '/api/attempts/$id/submit'
      path: '/$id/submit'
      fullPath: '/api/attempts/$id/submit'
      preLoaderRoute: typeof ApiAttemptsIdSubmitRouteImport
      parentRoute: typeof ApiAttemptsRoute
    }
    '/api/evaluations/$id/confirm': {
      id: '/api/evaluations/$id/confirm'
      path: '/$id/confirm'
      fullPath: '/api/evaluations/$id/confirm'
      preLoaderRoute: typeof ApiEvaluationsIdConfirmRouteImport
      parentRoute: typeof ApiEvaluationsRoute
    }
    '/api/evaluations/$id/report': {
      id: '/api/evaluations/$id/report'
      path: '/$id/report'
      fullPath: '/api/evaluations/$id/report'
      preLoaderRoute: typeof ApiEvaluationsIdReportRouteImport
      parentRoute: typeof ApiEvaluationsRoute
    }
    '/api/papers/$id/regenerate-slot': {
      id: '/api/papers/$id/regenerate-slot'
      path: '/regenerate-slot'
      fullPath: '/api/papers/$id/regenerate-slot'
      preLoaderRoute: typeof ApiPapersIdRegenerateSlotRouteImport
      parentRoute: typeof ApiPapersIdRoute
    }
    '/api/questions/$id/approve': {
      id: '/api/questions/$id/approve'
      path: '/approve'
      fullPath: '/api/questions/$id/approve'
      preLoaderRoute: typeof ApiQuestionsIdApproveRouteImport
      parentRoute: typeof ApiQuestionsIdRoute
    }
    '/api/evaluations/$id/items/$itemId': {
      id: '/api/evaluations/$id/items/$itemId'
      path: '/$id/items/$itemId'
      fullPath: '/api/evaluations/$id/items/$itemId'
      preLoaderRoute: typeof ApiEvaluationsIdItemsItemIdRouteImport
      parentRoute: typeof ApiEvaluationsRoute
    }
    '/api/syllabus/chapters/$id/scope': {
      id: '/api/syllabus/chapters/$id/scope'
      path: '/$id/scope'
      fullPath: '/api/syllabus/chapters/$id/scope'
      preLoaderRoute: typeof ApiSyllabusChaptersIdScopeRouteImport
      parentRoute: typeof ApiSyllabusChaptersRoute
    }
  }
}

interface ApiAttemptsRouteChildren {
  ApiAttemptsIdAnswerRoute: typeof ApiAttemptsIdAnswerRoute
  ApiAttemptsIdSubmitRoute: typeof ApiAttemptsIdSubmitRoute
}

const ApiAttemptsRouteChildren: ApiAttemptsRouteChildren = {
  ApiAttemptsIdAnswerRoute: ApiAttemptsIdAnswerRoute,
  ApiAttemptsIdSubmitRoute: ApiAttemptsIdSubmitRoute,
}

const ApiAttemptsRouteWithChildren = ApiAttemptsRoute._addFileChildren(
  ApiAttemptsRouteChildren,
)

interface ApiEvaluationsRouteChildren {
  ApiEvaluationsIdConfirmRoute: typeof ApiEvaluationsIdConfirmRoute
  ApiEvaluationsIdReportRoute: typeof ApiEvaluationsIdReportRoute
  ApiEvaluationsIdItemsItemIdRoute: typeof ApiEvaluationsIdItemsItemIdRoute
}

const ApiEvaluationsRouteChildren: ApiEvaluationsRouteChildren = {
  ApiEvaluationsIdConfirmRoute: ApiEvaluationsIdConfirmRoute,
  ApiEvaluationsIdReportRoute: ApiEvaluationsIdReportRoute,
  ApiEvaluationsIdItemsItemIdRoute: ApiEvaluationsIdItemsItemIdRoute,
}

const ApiEvaluationsRouteWithChildren = ApiEvaluationsRoute._addFileChildren(
  ApiEvaluationsRouteChildren,
)

interface ApiQuestionsIdRouteChildren {
  ApiQuestionsIdApproveRoute: typeof ApiQuestionsIdApproveRoute
}

const ApiQuestionsIdRouteChildren: ApiQuestionsIdRouteChildren = {
  ApiQuestionsIdApproveRoute: ApiQuestionsIdApproveRoute,
}

const ApiQuestionsIdRouteWithChildren = ApiQuestionsIdRoute._addFileChildren(
  ApiQuestionsIdRouteChildren,
)

interface ApiQuestionsRouteChildren {
  ApiQuestionsIdRoute: typeof ApiQuestionsIdRouteWithChildren
}

const ApiQuestionsRouteChildren: ApiQuestionsRouteChildren = {
  ApiQuestionsIdRoute: ApiQuestionsIdRouteWithChildren,
}

const ApiQuestionsRouteWithChildren = ApiQuestionsRoute._addFileChildren(
  ApiQuestionsRouteChildren,
)

interface ApiStudentsRouteChildren {
  ApiStudentsIdRoute: typeof ApiStudentsIdRoute
}

const ApiStudentsRouteChildren: ApiStudentsRouteChildren = {
  ApiStudentsIdRoute: ApiStudentsIdRoute,
}

const ApiStudentsRouteWithChildren = ApiStudentsRoute._addFileChildren(
  ApiStudentsRouteChildren,
)

interface ApiPapersIdRouteChildren {
  ApiPapersIdRegenerateSlotRoute: typeof ApiPapersIdRegenerateSlotRoute
}

const ApiPapersIdRouteChildren: ApiPapersIdRouteChildren = {
  ApiPapersIdRegenerateSlotRoute: ApiPapersIdRegenerateSlotRoute,
}

const ApiPapersIdRouteWithChildren = ApiPapersIdRoute._addFileChildren(
  ApiPapersIdRouteChildren,
)

interface ApiSyllabusChaptersRouteChildren {
  ApiSyllabusChaptersIdScopeRoute: typeof ApiSyllabusChaptersIdScopeRoute
}

const ApiSyllabusChaptersRouteChildren: ApiSyllabusChaptersRouteChildren = {
  ApiSyllabusChaptersIdScopeRoute: ApiSyllabusChaptersIdScopeRoute,
}

const ApiSyllabusChaptersRouteWithChildren =
  ApiSyllabusChaptersRoute._addFileChildren(ApiSyllabusChaptersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiAttemptsRoute: ApiAttemptsRouteWithChildren,
  ApiBlueprintsRoute: ApiBlueprintsRoute,
  ApiEvaluationsRoute: ApiEvaluationsRouteWithChildren,
  ApiQuestionsRoute: ApiQuestionsRouteWithChildren,
  ApiStudentsRoute: ApiStudentsRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiPapersIdRoute: ApiPapersIdRouteWithChildren,
  ApiPapersGenerateRoute: ApiPapersGenerateRoute,
  ApiSyllabusChaptersRoute: ApiSyllabusChaptersRouteWithChildren,
  ApiSyllabusSubjectsRoute: ApiSyllabusSubjectsRoute,
  ApiTrackerStudentIdRoute: ApiTrackerStudentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
